var MyString = "I am a string";
console.log(MyString);
var string = 'I am a "double quoted " string';
console.log(string);
var sree = "\'single quote\'";
console.log(sree);
var a = "\"double quotaton\"";
console.log(a);
var b = "I am a girl \\ womam";
console.log(b); 
var c= "I am Sree \nI am from India";
console.log(c);
var d = "I am Sree.I am from India\n\tNow I live in Sweden";
console.log(d);
